apps/crud_alumnos/urls.py
from django.conf.urls import url
from apps.crud_alumnos.views import alumnosCreate, alumnosList, alumnosDelete, alumnosUpdate, alumnoShow, search, \
    estadoCreate,estadoDelete,estadoList,estadoShow,estadoUpdate, search_c

urlpatterns = [
    url(r'^nuevos/', alumnosCreate.as_view(), name='alumno_crear'),
    url(r'^listar/', alumnosList.as_view(), name='alumnos_listar'),
    url(r'^eliminar/(?P<pk>\d+)/$', alumnosDelete.as_view(), name='alumno_eliminar'),
    url(r'^modificar/(?P<pk>\d+)/$', alumnosUpdate.as_view(), name='alumno_editar'),
    url(r'^mostrar/(?P<pk>\d+)/$', alumnoShow.as_view(), name='alumno_mostrar'),
    url(r'^buscar/$', search, name='alumno_buscar'),
    #aqui inician las urls de estado
    url(r'^nuevo/', estadoCreate.as_view(), name='estado_crea'),
    url(r'^listo/', estadoList.as_view(), name='estado_lista'),
    url(r'^edita/(?P<pk>\d+)/$', estadoUpdate.as_view(), name='estado_edita'),
    url(r'^borrar/(?P<pk>\d+)/$', estadoDelete.as_view(), name='estado_borrar'),
    url(r'^ver/(?P<pk>\d+)/$', estadoShow.as_view(), name='estado_ver'),
    url(r'^busca/$', search_c, name='estado_busca')
]

proyectoactcompl/urls.py
from django.conf.urls import url, include

urlpatterns = [
url(r'^alumnos/', include(('apps.crud_alumnos.urls', 'apps'), namespace='alumnos')),
url(r'^estados/', include(('apps.crud_alumnos.urls', 'apps'), namespace='estados'))

]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<title>{% block title %}Formulario {% endblock %}</title>
</head>
<body>
<div class="container">
    {% block navbar %}
        <div class="row">
            <div class="col s12 m12 l12">
                <!-- Dropdown Structure -->
                <ul id="dropdown1" class="dropdown-content">
                    <li><a href="{% url 'alumnos:alumno_crear' %}">Registrar/Alumnos</a></li>
                    <li><a href="{% url 'alumnos:alumnos_listar' %}">Listar/Alumnos</a></li>
                    <li><a href="{% url 'alumnos:alumno_buscar' %}">Buscar/Filtrar/Alumnos</a></li>
                    <li><a href="{% url 'estados:estado_crea' %}">Registrar/Estados</a></li>
                    <li><a href="{% url 'estados:estado_lista' %}">Listar/Estados</a></li>
                    <li><a href="{% url 'estados:estado_busca' %}">Buscar/Filtrar/Estados</a></li>
                </ul>
                <nav class="light-blue accent-4">
                    <div class="nav-wrapper">
                        <a href="#" class="brand-logo">Inicio</a>
                        <ul class="right hide-on-med-and-down">

                            <li><a class="dropdown-trigger" href="#" data-target="dropdown1">Alumnos/Estados<i class="material-icons right">arrow_drop_down</i></a></li>
                            <li><a href="http://www.leonet.mx/" onclick="pageTracker._link(this.href); return false;">Conoce al Desarrollador</a></li>
                            <li><a href="#">Salir</a></li>
                            <!-- Dropdown Trigger -->
                        </ul>
                    </div>
                </nav>
           	</div>
        </div>

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
<div class="row">
    <div class="col s12 m12 l12">
        <footer class="page-footer cyan">
            <div class="footer-copyright">
                &copy; 2018 Ismael Soto Santamaria
            </div>
        </footer>
    </div>
</div>
</div>

	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/materialize.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $(".dropdown-trigger").dropdown();
            $('select').formSelect();
            $('.collapsible').collapsible();
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd'
            });
            $('.button-collapse').sideNav({});
            $('.materialboxed').materialbox();
            $(".button-collapse").sideNav();
            $('.scrollspy').scrollSpy();
            $('.modal').modal();
        });
    </script>
	{% block extrajs %}
	{% endblock %}

</body>
</html>