apps/crud_alumnos/urls.py
from django.conf.urls import url
from apps.crud_alumnos.views import alumnosCreate, alumnosList, alumnosDelete, alumnosUpdate, alumnoShow, search, \
    estadoCreate,estadoDelete,estadoList,estadoShow,estadoUpdate, search_c

urlpatterns = [
    url(r'^nuevos/', alumnosCreate.as_view(), name='alumno_crear'),
    url(r'^listar/', alumnosList.as_view(), name='alumnos_listar'),
    url(r'^eliminar/(?P<pk>\d+)/$', alumnosDelete.as_view(), name='alumno_eliminar'),
    url(r'^modificar/(?P<pk>\d+)/$', alumnosUpdate.as_view(), name='alumno_editar'),
    url(r'^mostrar/(?P<pk>\d+)/$', alumnoShow.as_view(), name='alumno_mostrar'),
    url(r'^buscar/$', search, name='alumno_buscar'),
    #aqui inician las urls de estado
    url(r'^nuevo/', estadoCreate.as_view(), name='estado_crea'),
    url(r'^listo/', estadoList.as_view(), name='estado_lista'),
    url(r'^edita/(?P<pk>\d+)/$', estadoUpdate.as_view(), name='estado_edita'),
    url(r'^borrar/(?P<pk>\d+)/$', estadoDelete.as_view(), name='estado_borrar'),
    url(r'^ver/(?P<pk>\d+)/$', estadoShow.as_view(), name='estado_ver'),
    url(r'^busca/$', search_c, name='estado_busca')
]

proyectoactcompl/urls.py
from django.conf.urls import url, include

urlpatterns = [
url(r'^alumnos/', include(('apps.crud_alumnos.urls', 'apps'), namespace='alumnos')),
url(r'^estados/', include(('apps.crud_alumnos.urls', 'apps'), namespace='estados'))

]

apps/crud_alumnos/models.py
from django.db import models
# Create your models here.


class carrera(models.Model):
    clave_oficial = models.CharField(max_length=15,primary_key=True)
    nombre = models.CharField(max_length=70)
    # aqui se crea el metodo __str__ para mostrar las carreras en el formulario de alumnos
    def __str__(self):
        return '{}'.format(self.nombre)


class estado(models.Model):
    id_estado = models.SmallIntegerField(primary_key=True)
    nombre_estado = models.CharField(max_length=70)
# aqui se crea el metodo __str__ para mostrar las carreras en el formulario de alumnos
    def __str__(self):
        return '{}'.format(self.nombre_estado)


class municipio(models.Model):
    id_municipio = models.SmallIntegerField(primary_key=True)
    nombre_municipio = models.CharField(max_length=70)
    estado = models.ForeignKey(estado, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.nombre_municipio)


class localidad(models.Model):
    id_localidad = models.BigIntegerField(primary_key=True)
    nombre_localidad = models.CharField(max_length=50)
    municipio = models.ForeignKey(municipio, null=True, blank=True, on_delete=models.CASCADE)
    # aqui se crea el metodo __str__ para mostrar las carreras en el formulario de alumnos

    def __str__(self):
        return '{}'.format(self.nombre_localidad)


class rol(models.Model):
    id_rol = models.IntegerField(primary_key=True)
    nombre_rol = models.CharField(max_length=50)
    # aqui se crea el metodo __str__ para mostrar las carreras en el formulario de alumnos
    def __str__(self):
        return '{}'.format(self.nombre_rol)


class alumnos(models.Model):
    nocontrol = models.BigIntegerField(primary_key=True)
    nombre = models.CharField(max_length=30)
    apellido_paterno = models.CharField(max_length=30)
    apellido_materno = models.CharField(max_length=30)
    email = models.CharField(max_length=50)
    telefono = models.BigIntegerField(20)
    fecha_nacimiento = models.DateField()
    sexo = models.CharField(max_length=1)
    calle = models.CharField(max_length=50)
    numero_exterior = models.CharField(max_length=50)
    numero_interior = models.CharField(max_length=50)
    colonia = models.CharField(max_length=50)
    password = models.CharField(max_length=100)
    estatus = models.CharField(max_length=1)
    carrera = models.ForeignKey(carrera, null=True, blank=True, on_delete=models.CASCADE)
    localidad = models.ForeignKey(localidad, null=True, blank=True, on_delete=models.CASCADE)
    rol = models.ForeignKey(rol, null=True, blank=True, on_delete=models.CASCADE)






"""
despues se ejecuta el comando para realizar la migración del modelo a la base de datos

 python manage.py makemigrations
 python manage.py migrate

se insertan datos a la base de datos con python manage.py shell

 from apps.crud_alumnos.models import carrera
"""

apps/crud_alumnos/forms.py
# aqui se Crea el formulario

from django import forms
from apps.crud_alumnos.models import alumnos,estado


class alumnosForm(forms.ModelForm):
    class Meta:
        model = alumnos
        fields = [
            'nocontrol',
            'nombre',
            'apellido_paterno',
            'apellido_materno',
            'email',
            'telefono',
            'fecha_nacimiento',
            'sexo',
            'calle',
            'numero_exterior',
            'numero_interior',
            'colonia',
            'password',
            'estatus',
            'carrera',
            'localidad',
            'rol'
        ]
        labels = {
            'nocontrol':'Numero de Control',
            'nombre':'Nombres',
            'apellido_paterno':'Apellido Paterno',
            'apellido_materno':'Apellido Materno',
            'email':'Correo Electronico',
            'telefono':'Numero de Telefono',
            'fecha_nacimiento':'Fecha de Nacimiento',
            'sexo':'Sexo',
            'calle':'Direccion',
            'numero_exterior':'Numero Exterior',
            'numero_interior':'Numero Interior',
            'colonia':'Colonia',
            'password':'Contraseña',
            'estatus':'Estatus',
            'carrera':'Carrera',
            'localidad':'Localidad',
            'rol':'Rol'
        }

        widgets = {
            'nocontrol':forms.TextInput(attrs={'class':'form-control'}),
            'nombre':forms.TextInput(attrs={'class':'form-control'}),
            'apellido_paterno':forms.TextInput(attrs={'class':'form-control'}),
            'apellido_materno':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control'}),
            'telefono':forms.TextInput(attrs={'class':'form-control'}),
            'fecha_nacimiento':forms.TextInput(attrs={'class':'datepicker'}),
            'sexo':forms.TextInput(attrs={'class':'form-control'}),
            'calle':forms.TextInput(attrs={'class':'form-control'}),
            'numero_exterior':forms.TextInput(attrs={'class':'form-control'}),
            'numero_interior':forms.TextInput(attrs={'class':'form-control'}),
            'colonia':forms.TextInput(attrs={'class':'form-control'}),
            'password':forms.PasswordInput(attrs={'class':'form-control'}),
            'estatus':forms.TextInput(attrs={'class':'form-control'}),
            'carrera':forms.Select(attrs={'class':'form-control'}),
            'localidad':forms.Select(attrs={'class':'form-control'}),
            'rol':forms.Select(attrs={'class':'form-control'})
        }

#aqui inicia el formulario de estado

class estadoForm(forms.ModelForm):
    class Meta:
        model = estado
        fields = [
            'id_estado',
            'nombre_estado'
            ]
        labels = {
            'id_estado':'Clave de Estado',
            'nombre_estado':'Nombre del Estado'
        }
        widgets = {
            'id_estado': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre_estado': forms.TextInput(attrs={'class': 'form-control'}),
        }

apps/crud_alumnos/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from apps.crud_alumnos.models import alumnos,estado
from apps.crud_alumnos.forms import alumnosForm,estadoForm
from apps.crud_alumnos.filters import alumnosFilter,estadoFilter
from django.urls import reverse_lazy
# Create your views here.


class alumnosCreate(CreateView):
    model = alumnos
    form_class = alumnosForm
    template_name = 'crudalumnos/alumnos_form.html'
    success_url = reverse_lazy('alumnos:alumnos_listar')


class alumnosList(ListView):
    queryset = alumnos.objects.order_by('nocontrol')
    template_name = 'crudalumnos/alumnos_list.html'
    paginate_by = 5


class alumnosUpdate(UpdateView):
    model = alumnos
    form_class = alumnosForm
    template_name = 'crudalumnos/alumnos_form.html'
    success_url = reverse_lazy('alumnos:alumnos_listar')


class alumnosDelete(DeleteView):
    model = alumnos
    template_name = 'crudalumnos/alumnos_delete.html'
    success_url = reverse_lazy('alumnos:alumnos_listar')


class alumnoShow(DetailView):
    model = alumnos
    template_name = 'crudalumnos/alumno_show.html'

# buscar o filtrar
# Para agregar la vista de búsqueda, se instala primero
# pip install django-filters
def search(request):
    alumnos_list = alumnos.objects.all()
    alumnos_filter = alumnosFilter(request.GET, queryset=alumnos_list)
    return render(request, 'crudalumnos/alumnos_list_filter.html', {'filter': alumnos_filter})
#aqui inicia la vista del crud estado
class estadoCreate(CreateView):
    model = estado
    form_class = estadoForm
    template_name = 'crudalumnos/estados_form.html'
    success_url = reverse_lazy('estados:estado_lista')


class estadoList(ListView):
    queryset = estado.objects.order_by('id_estado')
    template_name = 'crudalumnos/estados_list.html'
    paginate_by = 10


class estadoUpdate(UpdateView):
    model = estado
    form_class = estadoForm
    template_name = 'crudalumnos/estados_form.html'
    success_url = reverse_lazy('estados:estado_lista')


class estadoDelete(DeleteView):
    model = estado
    template_name = 'crudalumnos/estados_delete.html'
    success_url = reverse_lazy('estados:estado_lista')


class estadoShow(DetailView):
    model = estado
    template_name = 'crudalumnos/estado_show.html'

def search_c(request):
    estado_list = estado.objects.all()
    estado_filter = estadoFilter(request.GET, queryset=estado_list)
    return render(request, 'crudalumnos/estados_list_filter.html', {'filter': estado_filter})

templates/crudalumnos/alumno_show.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <p><strong>N&uacute;mero de control: </strong>{{ object.nocontrol }} </p>
        <p><strong>Nombre: </strong>{{ object.nombre }} </p>
        <p><strong>Apellido Paterno: </strong>{{ object.apellido_paterno }} </p>
        <p><strong>Apellido Materno: </strong>{{ object.apellido_materno }} </p>
        <p><strong>Correo Electronico:</strong> {{ alumnos.email }}</p>
        <p><strong>Telefono: </strong>{{ alumnos.telefono }}</p>
        <p><strong>Fecha de Nacimiento:</strong> {{ alumnos.fecha_nacimiento }}</p>
        <p><strong>Sexo:</strong> {{ alumnos.sexo }}</p>
        <p><strong>Direccion:</strong> {{ alumnos.calle }}</p>
        <p><strong>Numero Ext.:</strong> {{ alumnos.numero_exterior }}</p>
        <p><strong>Numero Int.: </strong>{{ alumnos.numero_interior }}</p>
        <p><strong>Colonia:</strong> {{ alumnos.colonia }}</p>
        <p><strong>Contrasena:</strong> {{ alumnos.password }}</p>
        <p><strong>Estatus: </strong>{{ alumnos.estatus }}</p>
        <p><strong>Carrera:</strong> {{ alumnos.carrera }}</p>
        <p><strong>Localidad:</strong> {{ alumnos.localidad }}</p>
        <p><strong>Rol:</strong> {{ alumnos.rol }}</p>



        <a class= "btn" href="{% url 'alumnos:alumnos_listar' %}">Ok</a>
        <a class= "btn blue" href="{% url 'alumnos:alumno_editar' object.nocontrol%}"><i class="material-icons">create</i></a>
        <a class="btn red" href="{% url 'alumnos:alumno_eliminar' object.nocontrol %}"><i class="material-icons">delete</i></a>
    </div>
</div>


{% endblock %}

templates/crudalumnos/alumnos_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
                {% csrf_token %}
                <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
                <button class="btn btn-danger red" type="submit">Sí, eliminar</button>
                <a class= "btn btn-default" href="{% url 'alumnos:alumnos_listar' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/crudalumnos/alumnos_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <button class="btn blue" type="submit">Guardar<i class="material-icons right">send</i></button>
	            <a class= "btn red" href="{% url 'alumnos:alumnos_listar' %}">Cancelar<i class="material-icons right">cancel</i></a>
            </form>
        </div>
    </div>
{% endblock %}

templates/crudalumnos/alumnos_list.html
{% extends 'base/base.html' %}

{% block content %}

     {% if object_list %}
    {% for alumnos in object_list %}

<div class="row">
    <div class="col s12 m7">
        <div class="card">
            <div class="card blue lighten-5">
                <div class="card-content black-text">
                    <span class="card-title">{{ alumnos.nocontrol }}</span>
                    <p>Nombre Completo: {{alumnos.nombre }} {{ alumnos.apellido_paterno }} {{ alumnos.apellido_materno}}</p>
                    <p>Correo Electronico: {{ alumnos.email }}</p>
                    <p>Telefono: {{ alumnos.telefono }}</p>
                    <p>Fecha de Nacimiento: {{ alumnos.fecha_nacimiento }}</p>
                    <p>Sexo: {{ alumnos.sexo }}</p>
                    <p>Direccion: {{ alumnos.calle }}</p>
                    <p>Numero Ext.: {{ alumnos.numero_exterior }}</p>
                    <p>Numero Int.: {{ alumnos.numero_interior }}</p>
                    <p>Colonia: {{ alumnos.colonia }}</p>
                    <p>Contrasena: {{ alumnos.password  }}</p>
                    <p>Estatus: {{ alumnos.estatus }}</p>
                    <p>Carrera: {{ alumnos.carrera }}</p>
                    <p>Localidad: {{ alumnos.localidad }}</p>
                    <p>Rol: {{ alumnos.rol }}</p>
        </div>
        <div class="card-action">
            <a class="btn green" href="{% url 'alumnos:alumno_mostrar' alumnos.nocontrol %}"><i class="material-icons">zoom_in</i> </a>
            <a class="btn blue" href="{% url 'alumnos:alumno_editar' alumnos.nocontrol %}"><i class="material-icons">create</i></a>
            <a class="btn red" href="{% url 'alumnos:alumno_eliminar' alumnos.nocontrol %}"><i class="material-icons">delete</i></a>
        </div>
      </div>
    </div>
  </div>
        {% endfor %}
                {% else %}
		            <h1>No hay registros de alumnos</h1>
		        {% endif %}

    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
                    <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>
</div>>
{% endblock%}

templates/crudalumnos/alumnos_list_filter.html
{% extends 'base/base.html' %}

{% block content %}
        {% if filter.qs %}
        {% for alumnos in filter.qs %}
<div class="row">
  <div class="s12 m12 l12">
    <h4>Filtrar por:</h4>
        <form method="get">
            <p>
            <div class="col s4 m4 l4">
            No. Control: &nbsp{{ filter.form.nocontrol }} &nbsp
            </div>
            <div class="col s4 m4 l4">
                Nombres: &nbsp {{ filter.form.nombre }} &nbsp
            </div>
            <div class="col s4 m4 l4">
                Carreras: &nbsp{{ filter.form.carrera }} &nbsp;&nbsp;
                <button class="btn blue" type="submit">Filtrar</button>
            </div>
            </p>
        </form>

   <div class="row">
    <div class="col s12 m7">
        <div class="card">
            <div class="card blue lighten-5">
                <div class="card-content black-text">
                    <span class="card-title">{{ alumnos.nocontrol }}</span>
                    <p>Nombre Completo: {{alumnos.nombre }} {{ alumnos.apellido_paterno }} {{ alumnos.apellido_materno}}</p>
                    <p>Correo Electronico: {{ alumnos.email }}</p>
                    <p>Telefono: {{ alumnos.telefono }}</p>
                    <p>Fecha de Nacimiento: {{ alumnos.fecha_nacimiento }}</p>
                    <p>Sexo: {{ alumnos.sexo }}</p>
                    <p>Direccion: {{ alumnos.calle }}</p>
                    <p>Numero Ext.: {{ alumnos.numero_exterior }}</p>
                    <p>Numero Int.: {{ alumnos.numero_interior }}</p>
                    <p>Colonia: {{ alumnos.colonia }}</p>
                    <input type="password" name="Contrasena" >
                    <p>Estatus: {{ alumnos.estatus }}</p>
                    <p>Carrera: {{ alumnos.carrera }}</p>
                    <p>Localidad: {{ alumnos.localidad }}</p>
                    <p>Rol: {{ alumnos.rol }}</p>
            </div>
                    <div class="card-action">
                    <a class="btn green" href="{% url 'alumnos:alumno_mostrar' alumnos.nocontrol %}"><i class="material-icons">zoom_in</i> </a>
                    <a class="btn blue" href="{% url 'alumnos:alumno_editar' alumnos.nocontrol %}"><i class="material-icons">create</i></a>
                    <a class="btn red" href="{% url 'alumnos:alumno_eliminar' alumnos.nocontrol %}"><i class="material-icons">delete</i></a>
                    </div>
                </div>
            </div>
        </div>
   </div>
  </div>
        {% endfor %}
                {% else %}
		            <h1>No hay registros de alumnos</h1>
		        {% endif %}
    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock%}

templates/crudalumnos/estado_show.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <p><strong>N&uacute;mero de control: </strong>{{ object.id_estado }} </p>
        <p><strong>Nombre: </strong>{{ object.nombre_estado }} </p>

        <a class= "btn" href="{% url 'estados:estado_lista' %}">Ok</a>
        <a class= "btn blue" href="{% url 'estados:estado_edita' object.id_estado %}"><i class="material-icons">create</i></a>
        <a class="btn red" href="{% url 'estados:estado_borrar' object.id_estado %}"><i class="material-icons">delete</i></a>
    </div>
</div>


{% endblock %}

templates/crudalumnos/estados_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
                {% csrf_token %}
                <h3>¿Desea eliminar el registro de {{ object.nombre_estado }}?</h3>
                <button class="btn btn-danger" type="submit">Sí, eliminar</button>
                <a class= "btn btn-default" href="{% url 'estados:estado_lista' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/crudalumnos/estados_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <button class="btn blue" type="submit">Guardar<i class="material-icons right">send</i></button>
	            <a class= "btn red" href="{% url 'estados:estado_lista' %}">Cancelar<i class="material-icons right">cancel</i></a>
            </form>
        </div>
    </div>
{% endblock %}

templates/crudalumnos/estados_list.html
{% extends 'base/base.html' %}

{% block content %}

     {% if object_list %}
    {% for estado in object_list %}

<div class="row">
    <div class="col s12 m7">
        <div class="card">
            <div class="card blue lighten-5">
                <div class="card-content black-text">
                    <span class="card-title">{{ estado.id_estado }}</span>
                    <h5>Nombre del Estado: 2{{ estado.nombre_estado }}</h5>
        </div>
        <div class="card-action">
            <a class="btn green" href="{% url 'estados:estado_ver' estado.id_estado %}"><i class="material-icons">zoom_in</i> </a>
            <a class="btn blue" href="{% url 'estados:estado_edita' estado.id_estado %}"><i class="material-icons">create</i></a>
            <a class="btn red" href="{% url 'estados:estado_borrar' estado.id_estado %}"><i class="material-icons">delete</i></a>
        </div>
      </div>
    </div>
  </div>
        {% endfor %}
                {% else %}
		            <h1>No hay registro de estados</h1>
		        {% endif %}

    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
                    <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock%}

templates/crudalumnos/estados_list_filter.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <h4>Filtrar por:</h4>
        <form method="get">
            <div class="col s4 m4 l4">
                Nombre de Estado: &nbsp {{ filter.form.nombre_estado }} &nbsp
                <button class="btn blue" type="submit">Filtrar</button>
            </div>
            </p>
        </form>
        <table class="striped">
	        <thead>
		        <tr>
			        <th>Clave de Estado</th>
			        <th>Nombre de Estado</th>
                </tr>
            </thead>
            <tbody>
            {% if filter.qs %}
                {% for estado in filter.qs %}
		        <tr>
			        <td>{{ estado.id_estado }}</td>
			        <td>{{ estado.nombre_estado }}</td>
			        <td>
				       <a class="btn green" href="{% url 'estados:estado_ver' estado.id_estado %}"><i class="material-icons">zoom_in</i> </a>
                        <a class="btn blue" href="{% url 'estados:estado_edita' estado.id_estado %}"><i class="material-icons">create</i></a>
                        <a class="btn red" href="{% url 'estados:estado_borrar' estado.id_estado %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registro de estado</h1>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>

    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock%}